# Generated by Django 2.2.5 on 2020-04-22 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_vendor_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='number_of_reviews',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='VendorReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 32, 1, 50541, tzinfo=utc))),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Customer')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Vendor')),
            ],
        ),
    ]
