# Generated by Django 3.0.5 on 2020-04-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200422_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviews',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
