# Generated by Django 3.0.5 on 2020-04-22 19:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200422_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorreviews',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
