# Generated by Django 3.0.5 on 2020-04-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200422_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
