# Generated by Django 3.0.5 on 2020-04-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WT', 'WAITING'), ('PC', 'PLACED'), ('DP', 'DISPATCHED'), ('CL', 'CANCELLED')], default='WT', max_length=2),
        ),
    ]
