# Generated by Django 2.2.5 on 2020-05-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
