# Generated by Django 3.0.5 on 2020-04-22 17:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 22, 17, 37, 18, 691079, tzinfo=utc)),
        ),
    ]
