# Generated by Django 3.0.5 on 2020-04-22 19:12

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200422_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=products.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
