# Generated by Django 3.0.5 on 2020-04-24 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200422_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='product',
            name='number_of_orders_received',
            field=models.IntegerField(default=0),
        ),
    ]
