# Generated by Django 2.2.5 on 2020-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200424_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_of_orders_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_orders_required',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
