# Generated by Django 2.2.5 on 2020-05-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200505_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_dispatch',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
