# Generated by Django 2.2.5 on 2020-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_last_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BAD'), (2, 'AVERAGE'), (3, 'GOOD'), (4, 'VERY GOOD'), (5, 'EXCELLENT')], default=3),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
